### ISSUE TITLE
Can we provide Dataset format ?

### ISSUE THREAD

**Issue by adarsh-dikhit** [robmanch/Image-Caption-Generator#2]
please Can you provide dataset format ?

**Comment by robmanch** [comment]
Hi Adarsh,

Could you please elaborate more on your question?

Thanks,
Robin Manchhanda

**Comment by ghost** [comment]
Structute of files ? Or can you give captions file

**Comment by robmanch** [comment]
I have updated the readme file, please have a look. Let me know if you still have any questions.

**Comment by adarsh-dikhit** [comment]
Thank you Sir

**Comment by adarsh-dikhit** [comment]
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_332/500877765.py in <module>
----> 1 vocab = build_vocab(clean_captions_dic)

~\AppData\Local\Temp/ipykernel_332/3373460079.py in build_vocab(captions)
      4         vocab.append(caption_list)
      5 
----> 6     vocab = set(" ".join(np.array(vocab).ravel()).split())
      7     print(f"Total number of words in vocabulary: {len(vocab)}")
      8     return vocab

TypeError: sequence item 0: expected str instance, list found

**Comment by adarsh-dikhit** [comment]
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7780/1948035618.py in <module>
     12     generator = data_generator(train_captions, train_img_encodings, tokenizer, max_length, vocab_size)
     13     # fit for one epoch
---> 14     history = model.fit(train_generator, epochs=1, 
     15                         steps_per_epoch=train_steps,
     16                         verbose=1, validation_data=(val_generator),

~\anaconda3\envs\nd\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~\anaconda3\envs\nd\lib\site-packages\tensorflow\python\framework\func_graph.py in autograph_handler(*args, **kwargs)
   1127           except Exception as e:  # pylint:disable=broad-except
   1128             if hasattr(e, "ag_error_metadata"):
-> 1129               raise e.ag_error_metadata.to_exception(e)
   1130             else:
   1131               raise

ValueError: in user code:

    File "C:\Users\Adarsh\anaconda3\envs\nd\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\Adarsh\anaconda3\envs\nd\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Adarsh\anaconda3\envs\nd\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\Adarsh\anaconda3\envs\nd\lib\site-packages\keras\engine\training.py", line 808, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\Adarsh\anaconda3\envs\nd\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\Adarsh\anaconda3\envs\nd\lib\site-packages\keras\engine\input_spec.py", line 227, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" '

    ValueError: Exception encountered when calling layer "model" (type Functional).
    
    Input 0 of layer "dense" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (None,)
    
    Call arguments received:
      • inputs=('tf.Tensor(shape=(None,), dtype=float32)', 'tf.Tensor(shape=(None,), dtype=float32)')
      • training=True
      • mask=None

**Comment by adarsh-dikhit** [comment]
vocab = set(" ".join(np.array(vocab).ravel()).split())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_23876/500877765.py in <module>
----> 1 vocab = build_vocab(clean_captions_dic)

~\AppData\Local\Temp/ipykernel_23876/3373460079.py in build_vocab(captions)
      4         vocab.append(caption_list)
      5 
----> 6     vocab = set(" ".join(np.array(vocab).ravel()).split())
      7     print(f"Total number of words in vocabulary: {len(vocab)}")
      8     return vocab

TypeError: sequence item 0: expected str instance, list found

**Comment by adarsh-dikhit** [comment]
Issue is resolved

**Comment by robmanch** [comment]
No problem, Adarsh
